import React from 'react';
import { useParams } from 'react-router-dom';
import './styles.css';

const unitPdfs = {
  'Unit 1: Differential equations of first order and first degree': ['https://storage.googleapis.com/eduzenith/cla/cla%20unit%201.pdf'],
  'Unit 2: Functions of several variables': ['https://storage.googleapis.com/eduzenith/cla/cla%20unit2.pdf'],
  'Unit 3: Applications of Functions of several Variable': ['https://storage.googleapis.com/eduzenith/cla/cla%20unit3.pdf'],
  'Unit 4: Linear Algebra':['https://storage.googleapis.com/eduzenith/cla/cla%20unit4.pdf'], 
  'Unit 5: Matrix Algebra (Eigen Values and Eigen Vectors)':['https://storage.googleapis.com/eduzenith/cla/cla%20unit5.pdf'],
  'Unit 6: Numerical solution of transcendental equations, Interpolation':['https://storage.googleapis.com/eduzenith/cla/cla%20unit6.pdf'],
  'Unit 1: DC Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: AC Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: DC Machines':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'], 
  'Unit 4: AC Machines':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'], 
  'Unit 5: Semiconductor Devices':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'], 
  'Unit 6: Transistors':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Computer Programming':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Conditional Statements and Loops':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Arrays and Strings':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Functions':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Pointers and Dynamic Memory Allocation':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Structure, Union and Files':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Engineering drawing ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Introduction to projections':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Projection of planes and solids':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Sections of solids and Development of Surfaces':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Computer Aided Design':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Drawing practice with AutoCAD':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction-Constitution':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Union Government and its Administration':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Election commission':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: State Government and its Administration':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Local Administration':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Union Judiciary':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Propositional logic':[],
  'Unit 2: Proof techniques':[],
  'Unit 3: Sets, relations and functions':[],
  'Unit 4: Introduction to counting':[],
  'Unit 5: Introduction to Graph Theory':[],
  'Unit 6: Graph Theory(Continuation)':[],
  'Unit 1: Oscillations':[],
  'Unit 2: Wave Optics':[],
  'Unit 3: Polarization and LASERS':[],
  'Unit 4: Holography, and Optical fibers':[],
  'Unit 5: Quantum Mechanics':[],
  'Unit 6: Semiconductor Physics':[],
  'Unit 1: Introduction to Managerial Economics and Financial Analysis':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Production':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Market Structure':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Capital and Capital Budgeting':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Financial Accounting':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Financial Statements':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to java':[],
  'Unit 2: Strings and Data Structures':[],
  'Unit 3: Inheritance and Interface':[],
  'Unit 4: File Handling and Exception Handling':[],
  'Unit 5: Packages and Multithreading':[],
  'Unit 6: Event Handling and Swings':[],
  'Unit 1: Linked Lists':[],
  'Unit 2: Stacks and Queues':[],
  'Unit 3: Sortings, Searching and Hashing':[],
  'Unit 4: Trees':[],
  'Unit 5: Trees and Operations':[],
  'Unit 6: Graphs':[],
  'Unit 1: The Multidisciplinary Nature of Environmental Studies and Natural Resources ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Ecosystems':['https://storage.googleapis.com/eduzenith/UNIT%20-2%20ES.pdf','https://storage.googleapis.com/eduzenith/Unit%20-%204%20ES.pdf'],
  'Unit 3: Biodiversity and It’s Conservation':['https://storage.googleapis.com/eduzenith/unit%20-3%20ES.pdf'],
  'Unit 4: Environmental Pollution':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Social Issues and the Environment':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Human Population and the Environment':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Probability and theorems in Probability ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Probability Distributions':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Moment Generating functions':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Order Statistics and Central Limit theorem':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Sampling Theory':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Large Sample Tests':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Automata':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Finite Automata ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Regular Languages ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Grammars ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Push Down Automata':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Turing Machine & Computability Theory':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Number systems and Boolean Algebra':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Introduction to Combinational Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Combinational Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Introduciton to Sequential Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Sequential Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Synchronous and Asynchronus Counters':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Algorithms':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Divide and conquer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Greedy method':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Dynamic Programming':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Backtracking, Branch and Bound':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: String Matching, NP-Hard and NP-Complete problems':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to database systems and Entity-Relationship data model':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Relational algebra and Relational calculus':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: SQL':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Normalization':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: File Organisation':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Transactions':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Operation Research':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Linear Programming':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Extension of Linear Programming':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Transportation and Assignment':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Queueing':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  "Unit 6: Costs and it's models":['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Basic Functional blocks of a computer and Data Representation':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Arithmetic and Logical Unit':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Control Unit':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Memory system design':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Input -output subsystems':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Pipelining and Parallel Processing':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Python Basics for Data Science':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Working with Data in Python':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Data Processing':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Data Analysis':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Data Visualization':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Machine Learning using Python':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Compilers':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Syntax Analysis -I':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Syntax Analysis -II ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Semantic Analysis':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Intermediate Code Generation and Code Optimization':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Code generation':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Web World and JavaScript':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: PHP basics':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Database Connectivity and Authentication':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Front-End Web UI Frameworks and Tools and jQuery':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Bootstrap':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: NodeJs':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction  to Operating System':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Process Management':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Process Synchronization':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Deadlocks':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Memory Management':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: File Systems And Secondary Storage Management':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction  to Computer Networks':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: The Data Link Layer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: The Network Layer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: The Transport Layer:':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: The Application Layer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Network Security':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Software Enginnering':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Software Project management':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Software design':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Coding':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Testing':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Software Reliability And Quality Management':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Basics of Linear Algebra':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Matrix Decomposition Algorithms':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Dimensions Reduction Algorithms':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Calculus':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Optimization':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Probability':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to AI Problems':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Heuristic Search Techniques':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Knowledge Representation':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Different Knowledge Representation Schemes':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Natural Language Processing':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Expert System Architecture':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Machine Learning':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Neural Networks and Genetic Algorithms':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Bayesian learning':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Computational Learning':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Instance based learning':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Advanced learning':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Data Mining and Data Processing':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Data Warehouse and OLAP Technology':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Association Rules in Large Databases':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Classification':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Cluster Analysis':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Outlier analysis':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Number system and Sequence & Series':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Arithmetic and Algebra':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Geometry , Probability & Statistics':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Logical Reasoning and Analytical Reasoning':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Data Interpretation ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Verbal Ability':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Differential Equations of First order and First degree':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Linear differential equations of higher order':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Sequences and Series':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Functions of several variables':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Applications of Functions of several Variable':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Beta and Gamma Function':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Engineering Physics':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Electrostatics -1':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Electrostatics -2':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Magnetostatics ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: : Time varying fields ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6:: Semiconductor physics':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Engineering Drawing':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Orthographic projections':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Projection of Solids':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Section of solid':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Introduction to AutoCAD':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Computer Graphics':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Basics of Electrical Technology':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Network Theorems':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Transient response of R, L, C circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Three phase network':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Introduction to DC motors':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: DC-DC Convertors':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to C':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Arrays':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3:Functions':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Structure & Union':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Pointers':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Data Structures':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to  Signals and Systems':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Continuous time LTI Systems':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Fourier series':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Continuous time Fourier Transform':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5:Laplace Transform ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Sampling':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Probability':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Random Variables':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Distributions':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4:Functions of Random variables ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Inequality and Generating functions':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Order statistics':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Number Systems and Boolean Algebra':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2:Combinational Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Sequential Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Counters and Registers':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Encoder,Decoder,Multiplexer,Demultiplexer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Memory Structure and Timing':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Block diagrams and SFG':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Mathematical modeling of Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Time response Analysis':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4:Root locus and RH Criteria':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Frequency Domain Representation':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: State variables and State model,':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Random Process':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Power Spectral Density':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Review of signals and systems':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Amplitude and Angle Modulation':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Quantization and DPCM, DM':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6:Noise ':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: 8086 microprocessor':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: MIPS architecture':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Introduction to Processor':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Pipelining':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Memory Hierarchy':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Memory and Operating System':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Linear Algebra':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Eigen values and Eigen vectors':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Multiple integrals':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Vector calculus':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Root finding Methods and Interpolation':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Numerical integration and numerical solution of IVP':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: : Review of C and Programming in C++':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: : OOP in C++':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Inheritance and Polymorphism':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Type Casting & Exceptions':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Classes Templates & STL':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: File handling and Multithreading':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Electronics':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Diodes':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: PN Diode Applications':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: MOSFETs':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: BJT Characteristics':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Transistor Biasing and Stabilization-BJT':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Basic concepts of Networks':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Transient analysis of First order Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Transient analysis of Second order Circuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Circuit Analysis Using Laplace Transform':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Two Port Network parameters':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: State Space Models For Electrical Networks':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: MOSFET Biasing and Its Small Signal Analysis':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Multi-Stage Amplifiers & Differential Amplifiers of MOSFET':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Current mirrors in MOSFETs':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: CMOScircuits':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: BJT- Configurations and Multi stage amplifiers':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: BJT- Differential amplifiers and Current mirrors':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Digital Signal Processing':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Discrete Time Fourier Transform (DTFT)':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Discrete Fourier Transform (DFT) and Fast Fourier Transform (FFT)':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Z transforms':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Filter Concepts':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Realization Of Digital Filters':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: HDL for Digital System Designs':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: HDL for Digital System Designs':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Finite State Machines':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: HDL for Finite State Machines':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Digital Systems modeling':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: HDL Modeling of USB Protocol Analyzer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Feedback Amplifiers':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Operational Amplifiers':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Wave shaping circuits & Oscillators':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: DC-DC Converters':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: PLL':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Data Converters':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Introduction to Electromagnetic waves and Guided media':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: Wave Propagation':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Wave propagation at interfaces':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Transmission Lines: Parameters':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Waveguides-I':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Waveguides-II':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 1: Data communication Components':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 2: LAN':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 3: Data Link Layer and Medium Access Sub Layer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 4: Network Layer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 5: Transport Layer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf'],
  'Unit 6: Application Layer':['pdf1.pdf', 'pdf2.pdf', 'pdf3.pdf', 'pdf4.pdf']

};

const UnitDetail = () => {
  const { subjectName, unitName } = useParams();
  const pdfs = unitPdfs[unitName] || [];

  return (
    <div>
      <header>
        <div className="header-content">
          <h1>{unitName}</h1>
        </div>
      </header>
      <main>
        <div className="introduction">
          <h2>{subjectName} - PDFs</h2>
        </div>
        <h3>PDFs</h3>
        <div className="pdf-list">
          {pdfs.map((pdf, index) => (
            <div key={index} className="pdf-item">
              <a href={`${pdf}`} target="_blank" rel="noopener noreferrer">{pdf}</a>
            </div>
          ))}
        </div>
      </main>
      <footer>
        <p className="fc">&copy; 2024 EduZenith. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default UnitDetail;
